name: Smoke test release
on:
  release:
    types: [published]
jobs:
  test-wp:
    name: Run smoke test on L-minus ${{ matrix.wp }} WordPress version
    runs-on: ubuntu-18.04
    strategy:
      matrix: 
        wp: [ '1', '2' ]
    steps:

      - name: Create dirs.
        run: |
              mkdir -p code/woocommerce
              mkdir -p package/woocommerce
              mkdir -p tmp/woocommerce
              mkdir -p node_modules

      - name: Checkout code.
        uses: actions/checkout@v2
        with:
          path: package/woocommerce

      - name: Run npm install.
        working-directory: package/woocommerce
        run: npm install

      - name: Load docker images and start containers.
        working-directory: package/woocommerce
        run: npx wc-e2e docker:up

      - name: Move current directory to code. We will install zip file in this dir later.
        run: mv ./package/woocommerce/* ./code/woocommerce

      - name: Download WooCommerce release zip
        working-directory: tmp
        run: |
          curl -L ${{ github.event.release.zipball_url }} > woocommerce.zip
          unzip woocommerce.zip -d woocommerce
          mv woocommerce/woocommerce/* ../package/woocommerce/

      - name: Run tests command.
        working-directory: code/woocommerce
        env:
          LATEST_WP_VERSION_MINUS: ${{ matrix.wp }}
        run: npx wc-e2e test:e2e
