name: Get Workflow and Job IDs

on:
  push:
    branches:
      - main

jobs:
  get-id:
    runs-on: ubuntu-latest
    steps:
    - name: Get workflow name
      run: echo "## Workflow name ${{ github.workflow }}"
    - name: Get job name
      run: echo "## Job name ${{ github.job }}"
    - name: Use API to get job ID
      uses: octokit/rest@v18
    - name: Parse job ID from API response
      run: |
        job_id=$(jq '.jobs[] | select(.name == "get-id") | .id' <<< $GITHUB_OUTPUT)
        echo "## Job ID: $job_id"