name: Get Workflow and Job IDs

on:
  push:
    branches:
      - main

jobs:
  print_ids:
    runs-on: ubuntu-latest
    steps:
      - name: Get Job ID from GH API
        id: get-job-id
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
            job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
            echo $job_id
            echo "job_id=$job_id" >> $GITHUB_OUTPUT  
      - name: Display Job ID
        run: |
         echo Job ID: ${{ steps.get-job-id.outputs.job_id }}

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           job_name: ${{ github.job }}
     
      - name: Output Job ID
        run: echo ${{ steps.jobs.outputs.job_id }}

      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.html_url }}