name: Get Workflow and Job IDs

on:
  push:
    branches:
      - main

jobs:
  print_ids:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow ID
        id: get_workflow_id
        run: echo "Workflow ID $GITHUB_RUN_ID"
      - name: Get Job ID
        id: get_job_id
        run: echo "Job ID ${{ github.job.job_id }}"
      - name: Print IDs
        run: |
          echo "Workflow ID: ${{ steps.get_workflow_id.outputs.workflow_id }}"
          echo "Job ID: ${{ steps.get_job_id.outputs }}"