name: Notify Slack on PR with Automation Label

on:
  pull_request:
    types: [labeled]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: >
      (github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'Automation'))
    steps:
      - name: Dummy Action Instead of Slack Notification
        run: |
          echo "This is a test. The PR has the Automation label."
          echo "Title: ${{ github.event.pull_request.title }}"
          echo "Opened By: ${{ github.event.pull_request.user.login }}"
          echo "Description: ${{ github.event.pull_request.body }}"
