name: Run smoke tests against plugins
on: pull_request
jobs:
  test-plugins:
    name: Smoke tests with ${{ matrix.plugins }} plugin installed
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - plugin: 'WooCommerce Payments'
            repo: 'automattic/woocommerce-payments'
          - plugin: 'Facebook for WooCommerce'
            repo: 'woocommerce/facebook-for-woocommerce'
          - plugin: 'WooCommerce Shipping & Tax'
            repo: 'woocommerce/woocommerce-services'
          - plugin: 'WooCommerce Subscriptions'
            repo: MY_TEST_SECRET
            private: true
        # plugins: [ 'automattic/woocommerce-payments', 'woocommerce/facebook-for-woocommerce', 'automattic/woocommerce-services', 'MY_TEST_SECRET']
        # pluginNames: [ 'WooCommerce Payments', 'Facebook for WooCommerce', 'WooCommerce Shipping & Tax', 'WooCommerce Subscriptions' ]
    steps:

      - name: Create ${{ matrix.plugin }} and ${{ matrix.repo }} and ${{ matrix.private }}.
        run: echo ${{ secrets[matrix.MY_TEST_SECRET] }}
