name: Run smoke tests against plugins
on: pull_request
jobs:
  test-plugins:
    name: Smoke tests with ${{ matrix.plugins }} plugin installed
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - plugin: 'WooCommerce Payments'
            repo: 'automattic/woocommerce-payments'
          - plugin: 'Facebook for WooCommerce'
            repo: 'woocommerce/facebook-for-woocommerce'
          - plugin: 'WooCommerce Shipping & Tax'
            repo: 'woocommerce/woocommerce-services'
          - plugin: 'WooCommerce Subscriptions'
            repo: MY_TEST_SECRET
            private: true
    steps:
      - name: test a private
        if: ${{ success() && matrix.private }}
        run: echo ''
      - name: Create ${{ matrix.plugin }} and ${{ matrix.repo }}
        env: 
          SOMETHING: ${{ matrix.private && secrets[matrix.repo] || matrix.repo }}
        run: echo $SOMETHING
