name: Notify Slack on PR with Automation Label

on:
  pull_request:
    types: [labeled]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: >
      (github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'Automation'))
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
                "text": "New Pull Request ready for QA review!",
                "blocks": [
                {
                    "type": "section",
                    "text": {
                    "type": "mrkdwn",
                    "text": "*New Pull Request with Automation Label*"
                    }
                },
                {
                    "type": "section",
                    "block_id": "section567",
                    "fields": [
                    {
                        "type": "mrkdwn",
                        "text": "*Title:*\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                    },
                    {
                        "type": "mrkdwn",
                        "text": "*Opened By:*\n<${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>"
                    }
                    ]
                },
                {
                    "type": "section",
                    "block_id": "section789",
                    "text": {
                    "type": "mrkdwn",
                    "text": "*Description:*\n${{ github.event.pull_request.body }}"
                    }
                }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}