name: PR Workflow - Cypress Directory Changes with Slack Notification

on:
  pull_request:
    types: [ready_for_review, review_requested, reopened, synchronize]

jobs:
  notify_slack:
    if: |
      contains(github.event.pull_request.changed_files, 'test/cypress/') &&
      (github.event.pull_request.requested_reviewers != null || 
       github.event.pull_request.requested_teams != null)
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
                "text": "*${{ github.event.pull_request.title }}* opened by *${{ github.event.pull_request.user.login }}* is ready for review! \n${{ github.event.pull_request.html_url }} \n*Description:* ${{ github.event.pull_request.body }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}