name: Notify Slack on PR with Automation Label

on:
  pull_request:
    types: [labeled]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: >
      (github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'Automation'))
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
                "text": "${{ github.event.pull_request.title }} opened by ${{ github.event.pull_request.user.login }} is ready for review! ${{ github.event.pull_request.html_url }} \n*Description:* ${{ github.event.pull_request.body }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}